### PR TITLE
Move to xstream

### PR DESCRIPTION
**Pull request by perrin4869**
Hm... I was trying to get this driver to work as is with modern Cycle.js as in the current examples, for example [here](http://cycle.js.org/), but this driver needed a significant rewrite work.
Good news is, I managed to make it work, and here is the PR making it happen!
Bad news... well it's a lot of differences, mostly breaking changes. Will need a bump to v3.0.0...

### CODE REVIEW

**Comment by perrin4869** [comment]
@cgeorg any updates on this? Any chance you could release a v3.0 of this PR?

**Comment by cgeorg** [comment]
I have fallen out of the loop on cycle updates, but this code looks good, and seems to mimic the example read-only WS driver in the docs, so let's do it.

**Comment by cgeorg** [comment]
Having difficulties w/SSH and github auth - I'll this published when I can.

**Comment by cgeorg** [comment]
Ok, published

**Comment by perrin4869** [comment]
Thanks!! Everything is working like charm now :)

**Pull request merged**
